# File: .github/workflows/workflow.yml

on: workflow_dispatch

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az group create --name casanova-21-vm-rg --location eastus
          az vm create --resource-group casanova-21-vm-rg --name casanova-21-vm --image Ubuntu2204 --admin-username azureuser --generate-ssh-keys
