name: container
on: workflow_dispatch

jobs:
  node-docker:
    runs-on: arc-runner-set
    container:
      image: casanova21/ubuntu-docker:latest
    steps:
         - name: Log the node version
           run: |
             docker images
