name: container
on: workflow_dispatch

jobs:
  node-docker:
    runs-on: arc-runner-set
    container:
      image: node:14.15.0-alpine3.12
    steps:
         - name: Log the node version
           run: |
             node -v
             cat /etc/os-release
             sleep 120
