name: hello-world-container
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: arc-runner-set
    container:
      image: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
        echo "Hello, world!"
        sleep 60
