name: hello-world-container
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: casanova-21-private-networking-runner
    container:
      image: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo "Hello, world!"
          sleep 10
