name: Matrix

on:
  workflow_dispatch:

jobs:
  run-matrix:
    strategy:
        matrix:
          os: [tesla-runners]
          version: [1,2,3,4,5,6,7,8,9,10]
    runs-on: ${{ matrix.os }}
    container:
      image: ubuntu
    steps:
      - name: simple
        run: |
          echo "Hello from "${{ matrix.version }}""
