name: Run Regression Tests on GPU

on:
  workflow_dispatch:
  
jobs:
  regression-gpu2:
    # creates workflows for CUDA 11.6 & CUDA 11.7 on ubuntu
    runs-on: [ubuntu-latest]
    steps:
      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: "${{ github.job }}"  # if job.<job-id>.name is not specified, this works too
      - name: Output Current Job Log URL
        run: echo ${{ steps.jobs.outputs.job_id }}
      - run: https://api.github.com/repos/${{ github.repository_owner }}/${GITHUB_REPOSITORY#*/}/actions/jobs/${{ github.run_id }}/rerun
      - name: Fail
        run: |
          echo "Executing a failing command"
          touch /file.txt
    outputs:
      job_id:  ${{ steps.jobs.outputs.job_id }}
  retry:
    needs: regression-gpu2
    runs-on: [ubuntu-latest]
    if: always() && (needs.regression-gpu.result != 'success')
    steps:
      - run: echo "hi"
      - run: echo ${{ needs.regression-gpu.outputs.job_id }}
      - name: Re-run on failure2
        if: always()
        #if: ${{ always() && contains(needs.*.result, 'failure') }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/jobs/${{ needs.regression-gpu.outputs.job_id }}/rerun
