name: Run Regression Tests on GPU

on:
  workflow_dispatch:
  
jobs:
  regression-gpu:
    # creates workflows for CUDA 11.6 & CUDA 11.7 on ubuntu
    runs-on: [ubuntu-latest]
    steps:
      - name: Fail
        run: |
          echo "Executing a failing command"
          touch /file.txt
      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: "${{ github.job }}"  # if job.<job-id>.name is not specified, this works too
      - name: Output Current Job Log URL
        run: echo ${{ steps.jobs.outputs.job_id }}
      - run: https://api.github.com/repos/${{ github.repository_owner }}/${GITHUB_REPOSITORY#*/}/actions/jobs/${{ github.run_id }}/rerun
    outputs:
      job_id:  ${{ steps.jobs.outputs.job_id }}
