name: Run Regression Tests on GPU

on:
  workflow_dispatch:
  
jobs:
  regression-gpu:
    # creates workflows for CUDA 11.6 & CUDA 11.7 on ubuntu
    runs-on: [ubuntu-latest]
    steps:
      - name: Fail
        run: |
          echo "Executing a failing command"
          touch /file.txt
      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: "${{ github.job }}"  # if job.<job-id>.name is not specified, this works too
      - name: Output Current Job Log URL
        run: echo ${{ steps.jobs.outputs.job_id }}
      - run: https://api.github.com/repos/${{ github.repository_owner }}/${GITHUB_REPOSITORY#*/}/actions/jobs/${{ github.run_id }}/rerun
     outputs:
       job_id:  ${{ steps.jobs.outputs.job_id }}

      #- run: |
      #    curl -L \
      #    -H "Accept: application/vnd.github+json" \
      #    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #    -H "X-GitHub-Api-Version: 2022-11-28" \
      #    https://api.github.com/repos/${{ github.repository }}/actions/jobs/${{ steps.jobs.outputs.job_id }}
  #retry:
  #  needs: regression-gpu
  #  runs-on: [self-hosted, regression-test-gpu]
  #  if: always() && (needs.regression-gpu.result != 'success')
  #  steps:
  #    - run: echo "hi"
  #    - run: echo ${{ needs.regression-gpu.outputs.job_id }}
  #    - name: Re-run on failure
  #      if: always()
  #      #if: ${{ always() && contains(needs.*.result, 'failure') }}
  #      run: |
  #        curl -L \
  #        -X POST \
  #        -H "Accept: application/vnd.github+json" \
  #        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
  #        -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/jobs/${{ needs.regression-gpu.outputs.job_id }}/rerun
